# This is an example configuration file
# To learn more, see the full config.yaml reference: https://docs.continue.dev/reference

name: Example Config
version: 1.0.0
schema: v1

# Define which models can be used
# https://docs.continue.dev/customization/models
models:
 - name: Claude Sonnet 4.6
   provider: anthropic
   model: claude-sonnet-4-6
   apiKey: ${{ inputs.ANTHROPIC_API_KEY }}
   roles:
    - chat
    - edit
    - apply
   defaultCompletionOptions:
    contextLength: 200000
    maxTokens: 64000
   capabilities:
    - tool_use
    - image_input

# MCP Servers that Continue can access
# https://docs.continue.dev/customization/mcp-tools
mcpServers:
  - uses: anthropic/memory-mcp
